/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kg.ergo.demo;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {
    @SuppressWarnings("unused")
    private static final long MIN_INTERNVAL_MILSECONDS = 60000L;

    public String getGreeting() {
        return "Hello World!";
    }

    public static boolean isValidGuid(String str) {
        try {
            UUID.fromString(str);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public static void main(String[] args) {
        log.info(new App().getGreeting());
        String tenantId = "999";
        String convertTenant = tenantId.replaceAll("(.{8})(.{4})(.{4})(.{4})(.+)", "$1-$2-$3-$4-$5");
        log.info("The converted tenant id is: " + convertTenant);
        boolean valid = isValidGuid(convertTenant);
        log.info("The tenant id: ", String.valueOf(valid));

        // Format the milliseconds into a human-readable date and time
        Date date = new Date(1721296795039L);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        String formattedDate = formatter.format(date);
        log.info("Formatted date and time: " + formattedDate);

        Long lastUpdateTime = System.currentTimeMillis() - 55000;
        long currentTimeMillis = System.currentTimeMillis();
        log.info("Current time in milliseconds: " + currentTimeMillis);
        log.info("The last update time in milliseconds: " + lastUpdateTime);
        log.info("The elapsed time in milliseconds: " + (currentTimeMillis - lastUpdateTime));
    }
}
